Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20190226.0.0"
  
  config.vm.network :forwarded_port, guest: 22  , host: 2422, id: "ssh"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yaml"
  end
end
