Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20190731.0.0"
  
  config.vm.network :forwarded_port, guest: 22  , host: 2522, id: "ssh"
  config.vm.network :forwarded_port, guest: 9090, host: 9090
  
  config.vm.provision :docker
end
